#include "PresetManager.h"
#include "PluginProcessor.h"
#include "StorageManager.h"
#include <algorithm>

// Factory preset data - generated by CMake from presets/
// Uses separate namespace (FactoryPresetData) to avoid conflicts with icon BinaryData
#if HAS_FACTORY_PRESETS
    #include "FactoryPresetData.h"
#endif

PresetManager::PresetManager(juce::AudioProcessor& processor,
                             juce::AudioProcessorValueTreeState& apvts)
    : audioProcessor(processor)
    , parameters(apvts)
{
    // 1. Create directory structure
    initializePresetDirectories();

    // 2. Migrate existing presets from old location (data root → Presets/)
    migratePresetsIfNeeded();

    // 3. Install factory presets from BinaryData to disk (first launch or version update)
    installFactoryPresetsIfNeeded();

    // 4. Create in-memory factory preset (Init)
    loadFactoryPresets();

    // 5. Scan all presets from disk (includes installed factory presets)
    scanUserPresets();
}

void PresetManager::savePreset(const juce::String& presetName)
{
    auto presetDir = getUserPresetDirectory();

    // Ensure the directory exists
    if (!presetDir.exists())
        presetDir.createDirectory();

    juce::File presetFile = presetDir.getChildFile(presetName + ".xml");

    auto xml = createPresetXml(presetName);

    if (xml != nullptr)
    {
        bool success = xml->writeTo(presetFile);

        if (success)
        {
            currentPresetName = presetName;
            currentPresetModified = false;
            scanUserPresets(); // Refresh list
        }
    }
}

bool PresetManager::loadPreset(const juce::String& presetName, const juce::String& category)
{
    // Search user presets first
    for (size_t i = 0; i < userPresets.size(); ++i)
    {
        if (userPresets[i].name == presetName)
        {
            // When category is provided, require exact match to disambiguate duplicates
            if (category.isNotEmpty() && userPresets[i].category != category)
                continue;

            currentPresetIndex = static_cast<int>(i + factoryPresets.size());
            currentPresetCategory = userPresets[i].category;
            return loadPresetFromFile(userPresets[i].file);
        }
    }

    // Fall back to factory presets
    for (size_t i = 0; i < factoryPresets.size(); ++i)
    {
        if (factoryPresets[i].name == presetName)
        {
            currentPresetIndex = static_cast<int>(i);
            currentPresetCategory = factoryPresets[i].category;
            return loadPresetFromXml(factoryPresets[i].xml.get(), presetName);
        }
    }

    return false;
}

bool PresetManager::deletePreset(const juce::String& presetName, const juce::String& category)
{
    // Can only delete user presets
    for (auto& preset : userPresets)
    {
        if (preset.name == presetName)
        {
            // When category is provided, require exact match to disambiguate duplicates
            if (category.isNotEmpty() && preset.category != category)
                continue;
            if (preset.file.existsAsFile())
            {
            #if JUCE_IOS
                // iOS: moveToTrash() fails in sandboxed containers — use deleteFile()
                bool success = preset.file.deleteFile();
            #else
                bool success = preset.file.moveToTrash();
            #endif
                if (success)
                {
                    scanUserPresets(); // Refresh list
                    if (currentPresetName == presetName)
                    {
                        currentPresetName.clear();
                        currentPresetCategory.clear();
                        currentPresetIndex = -1;
                    }
                }
                return success;
            }
        }
    }
    return false;
}

void PresetManager::randomizeFromPresets()
{
    // Efficient randomization: sample a limited number of presets (max 30)
    // For each parameter, pick a value from a random sampled preset
    // This avoids scanning all 200+ presets while still providing musical results

    const int MAX_PRESET_SAMPLES = 30;
    std::vector<std::unique_ptr<juce::XmlElement>> sampledPresetXmls;

    // Combine all available presets
    std::vector<PresetInfo*> allPresets;
    for (const auto& preset : factoryPresets)
        allPresets.push_back(const_cast<PresetInfo*>(&preset));
    for (const auto& preset : userPresets)
        allPresets.push_back(const_cast<PresetInfo*>(&preset));

    // Handle edge case: no presets available
    if (allPresets.empty())
    {
        // Silently do nothing if no presets exist
        // User can still use the plugin with default/current values
        return;
    }

    // Sample random presets (up to MAX_PRESET_SAMPLES)
    juce::Random random(juce::Time::currentTimeMillis());
    int numToSample = juce::jmin(MAX_PRESET_SAMPLES, static_cast<int>(allPresets.size()));

    for (int i = 0; i < numToSample; ++i)
    {
        int randomIndex = random.nextInt(static_cast<int>(allPresets.size()));
        PresetInfo* presetInfo = allPresets[randomIndex];

        std::unique_ptr<juce::XmlElement> xml;

        if (presetInfo->isFactory && presetInfo->xml)
        {
            // Factory preset - clone the existing XML
            xml = std::make_unique<juce::XmlElement>(*presetInfo->xml);
        }
        else if (presetInfo->file.existsAsFile())
        {
            // User preset - load from file
            xml = juce::XmlDocument::parse(presetInfo->file);
        }

        if (xml != nullptr)
        {
            sampledPresetXmls.push_back(std::move(xml));
        }
    }

    // Handle edge case: failed to load any preset XMLs
    if (sampledPresetXmls.empty())
    {
        return;
    }

    // For each parameter, pick a random value from a random sampled preset
    for (auto* param : audioProcessor.getParameters())
    {
        if (auto* rangedParam = dynamic_cast<juce::RangedAudioParameter*>(param))
        {
            juce::String paramId = rangedParam->getParameterID();

            // Skip *_note parameters (MIDI mapping, not stored in presets)
            if (paramId.endsWith("_note"))
                continue;

            // Pick a random preset from our samples
            int randomPresetIndex = random.nextInt(sampledPresetXmls.size());
            auto* presetXml = sampledPresetXmls[randomPresetIndex].get();

            // Convert XML to ValueTree to access parameters
            auto tree = juce::ValueTree::fromXml(*presetXml);
            if (!tree.isValid())
                continue;

            // Find this parameter in the preset
            for (int i = 0; i < tree.getNumChildren(); ++i)
            {
                auto child = tree.getChild(i);
                if (child.hasType("PARAM"))
                {
                    auto childParamId = child.getProperty("id").toString();
                    if (childParamId == paramId)
                    {
                        auto value = child.getProperty("value");
                        float floatValue = static_cast<float>(value);
                        rangedParam->setValueNotifyingHost(rangedParam->convertTo0to1(floatValue));
                        break;
                    }
                }
            }
        }
    }

    // Mark as modified and clear current preset name
    currentPresetName.clear();
    currentPresetCategory.clear();
    currentPresetModified = true;
    currentPresetIndex = -1;
}

void PresetManager::savePresetAs(const juce::File& file)
{
    juce::File targetFile = file;

    // Ensure .xml extension
    if (!targetFile.hasFileExtension(".xml"))
        targetFile = targetFile.withFileExtension(".xml");

    auto presetName = targetFile.getFileNameWithoutExtension();
    auto xml = createPresetXml(presetName);

    if (xml != nullptr)
    {
        bool success = xml->writeTo(targetFile);

        if (success)
        {
            currentPresetName = presetName;
            currentPresetModified = false;
            scanUserPresets(); // Refresh list
        }
    }
}

bool PresetManager::loadPresetFromFile(const juce::File& file)
{
    if (!file.existsAsFile())
        return false;

    auto xml = juce::XmlDocument::parse(file);
    auto presetName = file.getFileNameWithoutExtension();
    return loadPresetFromXml(xml.get(), presetName);
}

juce::File PresetManager::getCurrentPresetFile() const
{
    // If no preset is loaded, return invalid file
    if (currentPresetIndex < 0)
        return juce::File();

    // Check if it's a factory preset
    if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
    {
        // Factory presets don't have files, return invalid
        return juce::File();
    }

    // It's a user preset - get the file
    int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
    if (userIndex >= 0 && userIndex < static_cast<int>(userPresets.size()))
    {
        return userPresets[userIndex].file;
    }

    return juce::File();
}

juce::StringArray PresetManager::getAllPresetNames() const
{
    juce::StringArray names;

    // Factory presets first
    for (const auto& preset : factoryPresets)
        names.add("[Factory] " + preset.name);

    // Then user presets
    for (const auto& preset : userPresets)
        names.add(preset.name);

    return names;
}

juce::StringArray PresetManager::getFactoryPresetNames() const
{
    juce::StringArray names;
    for (const auto& preset : factoryPresets)
        names.add(preset.name);
    return names;
}

juce::StringArray PresetManager::getUserPresetNames() const
{
    juce::StringArray names;
    for (const auto& preset : userPresets)
        names.add(preset.name);
    return names;
}

juce::File PresetManager::getUserPresetDirectory() const
{
    // Use StorageManager for cross-platform storage with iOS App Groups support
    return StorageManager::getInstance().getPresetsUserDirectory();
}

juce::File PresetManager::getFactoryPresetDirectory() const
{
    juce::File dir;

    #if JUCE_MAC
        dir = juce::File("/Library/Audio/Presets");
    #elif JUCE_WINDOWS
        dir = juce::File::getSpecialLocation(
            juce::File::commonApplicationDataDirectory);
    #elif JUCE_LINUX
        dir = juce::File("/usr/share");
    #endif

    // Use fixed name "AugmaticGRE" without version number for preset directory
    return dir.getChildFile(JucePlugin_Manufacturer)
              .getChildFile("AugmaticGRE");
}

bool PresetManager::loadNextPreset()
{
    // Get the current preset's category to stay within the same folder
    juce::String currentCategory;
    if (currentPresetIndex >= 0)
    {
        if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
        {
            currentCategory = factoryPresets[currentPresetIndex].category;
        }
        else
        {
            int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
            if (userIndex < static_cast<int>(userPresets.size()))
                currentCategory = userPresets[userIndex].category;
        }
    }

    // Find the next preset with the same category
    int startIndex = currentPresetIndex;
    int totalPresets = static_cast<int>(factoryPresets.size() + userPresets.size());

    if (totalPresets == 0)
        return false;

    // Search for next preset in same category
    for (int attempts = 0; attempts < totalPresets; ++attempts)
    {
        currentPresetIndex++;
        if (currentPresetIndex >= totalPresets)
            currentPresetIndex = 0; // Wrap around

        // Check if this preset matches the category
        juce::String candidateCategory;
        if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
        {
            candidateCategory = factoryPresets[currentPresetIndex].category;
        }
        else
        {
            int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
            if (userIndex < static_cast<int>(userPresets.size()))
                candidateCategory = userPresets[userIndex].category;
        }

        // Found a preset in the same category
        if (candidateCategory == currentCategory)
        {
            currentPresetCategory = currentCategory;
            if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
            {
                return loadPresetFromXml(factoryPresets[currentPresetIndex].xml.get(),
                                         factoryPresets[currentPresetIndex].name);
            }
            else
            {
                int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
                return loadPresetFromFile(userPresets[userIndex].file);
            }
        }
    }

    // If we get here, no other preset in same category - stay on current
    currentPresetIndex = startIndex;
    return false;
}

bool PresetManager::loadPreviousPreset()
{
    // Get the current preset's category to stay within the same folder
    juce::String currentCategory;
    if (currentPresetIndex >= 0)
    {
        if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
        {
            currentCategory = factoryPresets[currentPresetIndex].category;
        }
        else
        {
            int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
            if (userIndex < static_cast<int>(userPresets.size()))
                currentCategory = userPresets[userIndex].category;
        }
    }

    // Find the previous preset with the same category
    int startIndex = currentPresetIndex;
    int totalPresets = static_cast<int>(factoryPresets.size() + userPresets.size());

    if (totalPresets == 0)
        return false;

    // Search for previous preset in same category
    for (int attempts = 0; attempts < totalPresets; ++attempts)
    {
        currentPresetIndex--;
        if (currentPresetIndex < 0)
            currentPresetIndex = totalPresets - 1; // Wrap around

        // Check if this preset matches the category
        juce::String candidateCategory;
        if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
        {
            candidateCategory = factoryPresets[currentPresetIndex].category;
        }
        else
        {
            int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
            if (userIndex < static_cast<int>(userPresets.size()))
                candidateCategory = userPresets[userIndex].category;
        }

        // Found a preset in the same category
        if (candidateCategory == currentCategory)
        {
            currentPresetCategory = currentCategory;
            if (currentPresetIndex < static_cast<int>(factoryPresets.size()))
            {
                return loadPresetFromXml(factoryPresets[currentPresetIndex].xml.get(),
                                         factoryPresets[currentPresetIndex].name);
            }
            else
            {
                int userIndex = currentPresetIndex - static_cast<int>(factoryPresets.size());
                return loadPresetFromFile(userPresets[userIndex].file);
            }
        }
    }

    // If we get here, no other preset in same category - stay on current
    currentPresetIndex = startIndex;
    return false;
}

int PresetManager::getCurrentPresetIndex() const
{
    return currentPresetIndex;
}

void PresetManager::rescanUserPresets()
{
    // With security-scoped bookmark architecture, Documents is the single source of truth.
    // No sync needed — both standalone and AUv3 (with bookmark) read/write directly.
    scanUserPresets();
}

// Private helper methods

void PresetManager::initializePresetDirectories()
{
    // Use StorageManager to initialize all directories (including App Group on iOS)
    StorageManager::getInstance().initializeDirectories();
}

// Static Init preset XML — independent snapshot (not linked to any factory preset file)
static const char* kInitPresetXml = R"xml(
<AugmaticGRE presetName="Init" version="0.4.326" presetVersion="1.0" bpm="120">
  <PARAM id="grids_x" value="199"/>
  <PARAM id="grids_y" value="195"/>
  <PARAM id="chaos" value="0"/>
  <PARAM id="density_bd" value="53"/>
  <PARAM id="density_sd" value="46"/>
  <PARAM id="density_hh" value="255"/>
  <PARAM id="density_bd_acc" value="0"/>
  <PARAM id="density_sn_acc" value="0"/>
  <PARAM id="density_hh_acc" value="0"/>
  <PARAM id="bd_chaos" value="0"/>
  <PARAM id="sn_chaos" value="0"/>
  <PARAM id="hh_chaos" value="0"/>
  <PARAM id="bd_acc_chaos" value="0"/>
  <PARAM id="sn_acc_chaos" value="0"/>
  <PARAM id="hh_acc_chaos" value="0"/>
  <PARAM id="bd_engine_probability" value="0.00"/>
  <PARAM id="sn_engine_probability" value="0.00"/>
  <PARAM id="hh_engine_probability" value="0.00"/>
  <PARAM id="bd_acc_engine_probability" value="0.00"/>
  <PARAM id="sn_acc_engine_probability" value="0.00"/>
  <PARAM id="hh_acc_engine_probability" value="0.00"/>
  <PARAM id="bd_euclidean_steps" value="16"/>
  <PARAM id="sn_euclidean_steps" value="16"/>
  <PARAM id="hh_euclidean_steps" value="16"/>
  <PARAM id="bd_acc_euclidean_steps" value="16"/>
  <PARAM id="sn_acc_euclidean_steps" value="16"/>
  <PARAM id="hh_acc_euclidean_steps" value="16"/>
  <PARAM id="bd_euclidean_pulses" value="2"/>
  <PARAM id="sn_euclidean_pulses" value="1"/>
  <PARAM id="hh_euclidean_pulses" value="8"/>
  <PARAM id="bd_acc_euclidean_pulses" value="4"/>
  <PARAM id="sn_acc_euclidean_pulses" value="4"/>
  <PARAM id="hh_acc_euclidean_pulses" value="4"/>
  <PARAM id="bd_euclidean_start" value="1"/>
  <PARAM id="sn_euclidean_start" value="9"/>
  <PARAM id="hh_euclidean_start" value="1"/>
  <PARAM id="bd_acc_euclidean_start" value="1"/>
  <PARAM id="sn_acc_euclidean_start" value="1"/>
  <PARAM id="hh_acc_euclidean_start" value="1"/>
  <PARAM id="bd_swing" value="0.00"/>
  <PARAM id="sn_swing" value="0.00"/>
  <PARAM id="hh_swing" value="0.00"/>
  <PARAM id="bd_acc_swing" value="0.00"/>
  <PARAM id="sn_acc_swing" value="0.00"/>
  <PARAM id="hh_acc_swing" value="0.00"/>
  <PARAM id="bd_shift" value="63"/>
  <PARAM id="sn_shift" value="63"/>
  <PARAM id="hh_shift" value="63"/>
  <PARAM id="bd_acc_shift" value="63"/>
  <PARAM id="sn_acc_shift" value="63"/>
  <PARAM id="hh_acc_shift" value="63"/>
  <PARAM id="bd_humanize" value="0"/>
  <PARAM id="sn_humanize" value="0"/>
  <PARAM id="hh_humanize" value="0"/>
  <PARAM id="bd_acc_humanize" value="0"/>
  <PARAM id="sn_acc_humanize" value="0"/>
  <PARAM id="hh_acc_humanize" value="0"/>
  <PARAM id="bd_clock_ratio" value="8"/>
  <PARAM id="sn_clock_ratio" value="8"/>
  <PARAM id="hh_clock_ratio" value="8"/>
  <PARAM id="bd_acc_clock_ratio" value="8"/>
  <PARAM id="sn_acc_clock_ratio" value="8"/>
  <PARAM id="hh_acc_clock_ratio" value="8"/>
  <PARAM id="bd_probability_pre" value="100.00"/>
  <PARAM id="sn_probability_pre" value="100.00"/>
  <PARAM id="hh_probability_pre" value="100.00"/>
  <PARAM id="bd_acc_probability_pre" value="100.00"/>
  <PARAM id="sn_acc_probability_pre" value="100.00"/>
  <PARAM id="hh_acc_probability_pre" value="100.00"/>
  <PARAM id="bd_mute_pre" value="0"/>
  <PARAM id="sn_mute_pre" value="0"/>
  <PARAM id="hh_mute_pre" value="0"/>
  <PARAM id="bd_acc_mute_pre" value="0"/>
  <PARAM id="sn_acc_mute_pre" value="0"/>
  <PARAM id="hh_acc_mute_pre" value="0"/>
  <PARAM id="bd_solo_pre" value="0"/>
  <PARAM id="sn_solo_pre" value="0"/>
  <PARAM id="hh_solo_pre" value="0"/>
  <PARAM id="bd_acc_solo_pre" value="0"/>
  <PARAM id="sn_acc_solo_pre" value="0"/>
  <PARAM id="hh_acc_solo_pre" value="0"/>
  <PARAM id="linear_priority_bd" value="0"/>
  <PARAM id="linear_priority_sn" value="0"/>
  <PARAM id="linear_priority_hh" value="0"/>
  <PARAM id="linear_priority_bd_acc" value="0"/>
  <PARAM id="linear_priority_sn_acc" value="0"/>
  <PARAM id="linear_priority_hh_acc" value="0"/>
  <PARAM id="bd_probability_post" value="100.00"/>
  <PARAM id="sn_probability_post" value="100.00"/>
  <PARAM id="hh_probability_post" value="100.00"/>
  <PARAM id="bd_acc_probability_post" value="100.00"/>
  <PARAM id="sn_acc_probability_post" value="100.00"/>
  <PARAM id="hh_acc_probability_post" value="100.00"/>
  <PARAM id="bd_mute_post" value="0"/>
  <PARAM id="sn_mute_post" value="0"/>
  <PARAM id="hh_mute_post" value="0"/>
  <PARAM id="bd_acc_mute_post" value="0"/>
  <PARAM id="sn_acc_mute_post" value="0"/>
  <PARAM id="hh_acc_mute_post" value="0"/>
  <PARAM id="bd_solo_post" value="0"/>
  <PARAM id="sn_solo_post" value="0"/>
  <PARAM id="hh_solo_post" value="0"/>
  <PARAM id="bd_acc_solo_post" value="0"/>
  <PARAM id="sn_acc_solo_post" value="0"/>
  <PARAM id="hh_acc_solo_post" value="0"/>
  <PARAM id="bd_vel_value" value="120"/>
  <PARAM id="sn_vel_value" value="120"/>
  <PARAM id="hh_vel_value" value="127"/>
  <PARAM id="bd_acc_vel_value" value="120"/>
  <PARAM id="sn_acc_vel_value" value="120"/>
  <PARAM id="hh_acc_vel_value" value="120"/>
  <PARAM id="bd_vel_randomize" value="0.00"/>
  <PARAM id="sn_vel_randomize" value="0.00"/>
  <PARAM id="hh_vel_randomize" value="0.00"/>
  <PARAM id="bd_acc_vel_randomize" value="0.00"/>
  <PARAM id="sn_acc_vel_randomize" value="0.00"/>
  <PARAM id="hh_acc_vel_randomize" value="0.00"/>
  <PARAM id="accent_bender_instrument_bd" value="1"/>
  <PARAM id="accent_bender_instrument_sn" value="1"/>
  <PARAM id="accent_bender_instrument_hh" value="1"/>
  <PARAM id="accent_bender_instrument_bd_acc" value="1"/>
  <PARAM id="accent_bender_instrument_sn_acc" value="1"/>
  <PARAM id="accent_bender_instrument_hh_acc" value="1"/>
  <PARAM id="accent_bender_slider_2n" value="0.00"/>
  <PARAM id="accent_bender_slider_4n" value="0.00"/>
  <PARAM id="accent_bender_slider_4nt" value="0.00"/>
  <PARAM id="accent_bender_slider_8n" value="0.00"/>
  <PARAM id="note_duration" value="2"/>
  <PARAM id="linear_grid" value="2"/>
</AugmaticGRE>
)xml";

void PresetManager::loadFactoryPresets()
{
    factoryPresets.clear();

    // Factory presets from presets/ are now installed to disk by
    // installFactoryPresetsIfNeeded() and picked up by scanUserPresets().
    // Only the "Init" preset remains as a true in-memory factory preset.
    PresetInfo initPreset;
    initPreset.name = "Init";
    initPreset.isFactory = true;
    initPreset.xml = juce::XmlDocument::parse(kInitPresetXml);

    // Fallback: if static XML parse fails, use current APVTS defaults
    if (initPreset.xml == nullptr)
    {
        auto state = parameters.copyState();
        initPreset.xml = std::unique_ptr<juce::XmlElement>(state.createXml());
    }

    factoryPresets.push_back(std::move(initPreset));
}

juce::File PresetManager::getFactoryPresetsVersionFile() const
{
    return StorageManager::getInstance().getConfigDirectory()
               .getChildFile(".factory_presets_version");
}

void PresetManager::migratePresetsIfNeeded()
{
    auto& storage = StorageManager::getInstance();
    auto dataDir = storage.getDataDirectory();
    auto presetsDir = storage.getPresetsDirectory();

    // If Presets dir is same as data dir, no migration needed
    if (dataDir == presetsDir)
        return;

    // Check for XML files at the old location (data root)
    juce::Array<juce::File> rootXmlFiles;
    dataDir.findChildFiles(rootXmlFiles, juce::File::findFiles, false, "*.xml");

    // Check for category subfolders at the old location
    bool hasCategoryFolders = false;
    juce::Array<juce::File> subfolders;
    dataDir.findChildFiles(subfolders, juce::File::findDirectories, false);
    for (const auto& subfolder : subfolders)
    {
        juce::String name = subfolder.getFileName();
        if (name == "MidiMappings" || name == "Config" || name == "Presets")
            continue;
        juce::Array<juce::File> subXmlFiles;
        subfolder.findChildFiles(subXmlFiles, juce::File::findFiles, false, "*.xml");
        if (!subXmlFiles.isEmpty())
        {
            hasCategoryFolders = true;
            break;
        }
    }

    if (rootXmlFiles.isEmpty() && !hasCategoryFolders)
        return;

    if (!presetsDir.exists())
        presetsDir.createDirectory();

    // Move root-level XML files
    for (const auto& file : rootXmlFiles)
    {
        auto destFile = presetsDir.getChildFile(file.getFileName());
        if (!destFile.exists())
            file.moveFileTo(destFile);
    }

    // Move category subfolders
    for (const auto& subfolder : subfolders)
    {
        juce::String name = subfolder.getFileName();
        if (name == "MidiMappings" || name == "Config" || name == "Presets")
            continue;

        // Only move folders that contain XML files (preset categories)
        juce::Array<juce::File> catFiles;
        subfolder.findChildFiles(catFiles, juce::File::findFiles, false, "*.xml");
        if (catFiles.isEmpty())
            continue;

        auto destFolder = presetsDir.getChildFile(name);
        if (!destFolder.exists())
        {
            subfolder.moveFileTo(destFolder);
        }
        else
        {
            // Merge: move individual files that don't exist at destination
            for (const auto& catFile : catFiles)
            {
                auto destFile = destFolder.getChildFile(catFile.getFileName());
                if (!destFile.exists())
                    catFile.moveFileTo(destFile);
            }
        }
    }
}

void PresetManager::installFactoryPresetsIfNeeded()
{
#if HAS_FACTORY_PRESETS
    auto versionFile = getFactoryPresetsVersionFile();
    juce::String currentVersion = JucePlugin_VersionString;

    // Check if factory presets are already installed for this version
    if (versionFile.existsAsFile())
    {
        juce::String installedVersion = versionFile.loadFileAsString().trim();
        if (installedVersion == currentVersion)
            return;
    }

    // Factory presets are installed to the Factory/ subdirectory (never User/)
    auto factoryDir = StorageManager::getInstance().getPresetsFactoryDirectory();
    if (!factoryDir.exists())
        factoryDir.createDirectory();

    // Build new manifest from current BinaryData
    juce::StringArray newManifest;

    for (int i = 0; i < FactoryPresetData::namedResourceListSize; ++i)
    {
        juce::String originalFilename = FactoryPresetData::originalFilenames[i];

        if (!originalFilename.endsWithIgnoreCase(".xml"))
            continue;

        // Parse category from Category__Filename.xml convention
        juce::String category;
        juce::String presetFilename = originalFilename;

        int separatorIndex = originalFilename.indexOf("__");
        if (separatorIndex >= 0)
        {
            category = originalFilename.substring(0, separatorIndex);
            presetFilename = originalFilename.substring(separatorIndex + 2);
        }

        // Build relative path for manifest (e.g. "Category/Preset.xml" or "Preset.xml")
        juce::String relativePath = category.isNotEmpty()
            ? (category + "/" + presetFilename)
            : presetFilename;
        newManifest.add(relativePath);

        // Determine target directory (inside Factory/)
        juce::File targetDir = factoryDir;
        if (category.isNotEmpty())
        {
            targetDir = factoryDir.getChildFile(category);
            if (!targetDir.exists())
                targetDir.createDirectory();
        }

        juce::File targetFile = targetDir.getChildFile(presetFilename);

        // Get embedded data
        int dataSize;
        const char* data = FactoryPresetData::getNamedResource(
            FactoryPresetData::namedResourceList[i], dataSize);

        if (data == nullptr || dataSize <= 0)
            continue;

        if (!targetFile.exists())
        {
            // File doesn't exist — install it
            targetFile.replaceWithData(data, static_cast<size_t>(dataSize));
        }
        else
        {
            // File exists — only overwrite if embedded presetVersion is higher
            juce::String embeddedContent(data, static_cast<size_t>(dataSize));
            double embeddedVersion = parsePresetVersion(embeddedContent);
            double existingVersion = parsePresetVersion(targetFile.loadFileAsString());

            if (embeddedVersion > existingVersion)
            {
                targetFile.replaceWithData(data, static_cast<size_t>(dataSize));
            }
        }
    }

    // --- Filesystem-based cleanup: delete ANY .xml not in new manifest ---
    // Cleanup runs ONLY inside the Factory/ directory — User/ is NEVER touched.
    // This catches stale factory presets from ALL previous builds, including
    // pre-manifest ones that persist across iOS app reinstalls.
    for (const auto& file : factoryDir.findChildFiles(juce::File::findFiles, false, "*.xml"))
    {
        if (!newManifest.contains(file.getFileName()))
            file.deleteFile();
    }

    for (const auto& dir : factoryDir.findChildFiles(juce::File::findDirectories, false))
    {
        for (const auto& file : dir.findChildFiles(juce::File::findFiles, false, "*.xml"))
        {
            juce::String relativePath = dir.getFileName() + "/" + file.getFileName();
            if (!newManifest.contains(relativePath))
                file.deleteFile();
        }
    }

    // Clean up empty subfolders left after stale file deletion
    for (const auto& dir : factoryDir.findChildFiles(juce::File::findDirectories, false))
    {
        if (dir.findChildFiles(juce::File::findFiles, false, "*.xml").isEmpty())
            dir.deleteRecursively();
    }

    // Save new manifest and version marker
    saveFactoryManifest(newManifest);

    auto configDir = StorageManager::getInstance().getConfigDirectory();
    if (!configDir.exists())
        configDir.createDirectory();
    versionFile.replaceWithText(currentVersion);
#endif
}

void PresetManager::scanUserPresets()
{
    userPresets.clear();

    auto& storage = StorageManager::getInstance();

    // Helper lambda: scan a directory for presets (root + one level of subfolders)
    auto scanDirectory = [this](const juce::File& dir, bool isFactory)
    {
        if (!dir.exists())
            return;

        // Scan root-level .xml files
        for (const auto& file : dir.findChildFiles(juce::File::findFiles, false, "*.xml"))
        {
            PresetInfo info;
            info.name = file.getFileNameWithoutExtension();
            info.file = file;
            info.isFactory = isFactory;
            info.category = "";  // Root level
            userPresets.push_back(std::move(info));
        }

        // Scan one level of subfolders
        for (const auto& subfolder : dir.findChildFiles(juce::File::findDirectories, false))
        {
            juce::String folderName = subfolder.getFileName();

            for (const auto& file : subfolder.findChildFiles(juce::File::findFiles, false, "*.xml"))
            {
                PresetInfo info;
                info.name = file.getFileNameWithoutExtension();
                info.file = file;
                info.isFactory = isFactory;
                info.category = folderName;
                userPresets.push_back(std::move(info));
            }
        }
    };

    // Scan Factory directory (installed from BinaryData)
    scanDirectory(storage.getPresetsFactoryDirectory(), true);

    // Scan User directory (user-created presets)
    scanDirectory(storage.getPresetsUserDirectory(), false);

    // Sort presets by category first, then by name
    std::sort(userPresets.begin(), userPresets.end(),
        [](const PresetInfo& a, const PresetInfo& b)
        {
            if (a.category == b.category)
                return a.name < b.name;
            return a.category < b.category;
        });
}

bool PresetManager::loadPresetFromXml(juce::XmlElement* xml, const juce::String& presetName)
{
    if (xml == nullptr)
        return false;

    auto tree = juce::ValueTree::fromXml(*xml);
    if (!tree.isValid())
        return false;

    // Instead of replacing the entire state, update only the parameters that exist in the preset
    // This preserves any parameters not included in the preset (like *_note parameters)
    for (int i = 0; i < tree.getNumChildren(); ++i)
    {
        auto child = tree.getChild(i);
        if (child.hasType("PARAM"))
        {
            auto paramId = child.getProperty("id").toString();

            // Skip *_note parameters even if they exist in old presets
            if (paramId.endsWith("_note"))
                continue;

            auto value = child.getProperty("value");

            // Update the parameter value
            if (auto* param = parameters.getParameter(paramId))
            {
                float floatValue = static_cast<float>(value);
                param->setValueNotifyingHost(param->convertTo0to1(floatValue));
            }
        }
    }

    // Restore BPM from preset (standalone mode only)
    // In AUv3 mode, host controls tempo - ignore preset BPM
    if (auto* greProcessor = dynamic_cast<AugmaticGREProcessor*>(&audioProcessor))
    {
        if (greProcessor->wrapperType == juce::AudioProcessor::wrapperType_Standalone)
        {
            if (xml->hasAttribute("bpm"))
            {
                int bpm = xml->getIntAttribute("bpm", 120);
                greProcessor->setInternalClockBPM(static_cast<float>(bpm));
            }
        }
    }

    currentPresetName = presetName;
    currentPresetModified = false;

    if (onPresetLoaded)
        onPresetLoaded();

    return true;
}

std::unique_ptr<juce::XmlElement> PresetManager::createPresetXml(const juce::String& presetName)
{
    // Custom XML formatting for human-readable presets
    // Integer parameters saved as integers (no ".0"), floats rounded to 2 decimals
    auto xml = std::make_unique<juce::XmlElement>("AugmaticGRE");

    // Metadata attributes
    xml->setAttribute("presetName", presetName);
    xml->setAttribute("version", JucePlugin_VersionString);
    xml->setAttribute("presetVersion", "1.0");
    xml->setAttribute("dateCreated", juce::Time::getCurrentTime().toISO8601(true));

    // Save internal clock BPM (not in APVTS, restored only in standalone mode)
    if (auto* greProcessor = dynamic_cast<AugmaticGREProcessor*>(&audioProcessor))
    {
        xml->setAttribute("bpm", static_cast<int>(greProcessor->getInternalClockBPM()));
    }

    // Iterate through all parameters and format based on type
    for (auto* param : audioProcessor.getParameters())
    {
        if (auto* rangedParam = dynamic_cast<juce::RangedAudioParameter*>(param))
        {
            juce::String paramId = rangedParam->getParameterID();

            // Skip *_note parameters (managed by MIDI Mapping system)
            if (paramId.endsWith("_note"))
                continue;

            auto* paramElement = xml->createNewChildElement("PARAM");
            paramElement->setAttribute("id", paramId);

            // Format value based on parameter type
            if (auto* intParam = dynamic_cast<juce::AudioParameterInt*>(rangedParam))
            {
                // Integer parameters: no decimal point
                paramElement->setAttribute("value", intParam->get());
            }
            else if (auto* boolParam = dynamic_cast<juce::AudioParameterBool*>(rangedParam))
            {
                // Boolean parameters: 0 or 1 (no decimal)
                paramElement->setAttribute("value", boolParam->get() ? 1 : 0);
            }
            else if (auto* choiceParam = dynamic_cast<juce::AudioParameterChoice*>(rangedParam))
            {
                // Choice parameters: index as integer
                paramElement->setAttribute("value", choiceParam->getIndex());
            }
            else if (auto* floatParam = dynamic_cast<juce::AudioParameterFloat*>(rangedParam))
            {
                // Float parameters: round to 2 decimal places for readability
                // This is sufficient for float parameters mapped to MIDI CC values
                float value = floatParam->get();
                paramElement->setAttribute("value", juce::String(value, 2));
            }
        }
    }

    return xml;
}

juce::File PresetManager::getPresetsBaseDirectory() const
{
    // Use StorageManager for cross-platform storage with iOS App Groups support
    return StorageManager::getInstance().getPresetsDirectory();
}

std::vector<PresetManager::PresetItem> PresetManager::getAllPresetsWithCategories() const
{
    std::vector<PresetItem> items;

    // Add factory presets (no category)
    for (const auto& preset : factoryPresets)
    {
        PresetItem item;
        item.name = preset.name;
        item.category = "";  // Factory presets don't have categories
        item.isFactory = true;
        items.push_back(item);
    }

    // Add user presets with their categories
    for (const auto& preset : userPresets)
    {
        PresetItem item;
        item.name = preset.name;
        item.category = preset.category;
        item.isFactory = false;
        items.push_back(item);
    }

    return items;
}

juce::File PresetManager::getFactoryManifestFile() const
{
    return StorageManager::getInstance().getConfigDirectory()
               .getChildFile(".factory_presets_manifest");
}

void PresetManager::saveFactoryManifest(const juce::StringArray& relativePaths) const
{
    auto configDir = StorageManager::getInstance().getConfigDirectory();
    if (!configDir.exists())
        configDir.createDirectory();

    getFactoryManifestFile().replaceWithText(relativePaths.joinIntoString("\n"));
}

double PresetManager::parsePresetVersion(const juce::String& xmlContent)
{
    // Fast extraction: find presetVersion="..." without full XML parse
    int idx = xmlContent.indexOf("presetVersion=\"");
    if (idx < 0)
        return 0.0;

    idx += 15; // length of 'presetVersion="'
    int endIdx = xmlContent.indexOf(idx, "\"");
    if (endIdx < 0)
        return 0.0;

    return xmlContent.substring(idx, endIdx).getDoubleValue();
}